"""Analysis: convergence diagnostics, the BR-slope modulus estimator, sweeps,
market metrics, and plotting."""

from .convergence import (
    classify_run,
    empirical_lipschitz,
    fixed_point_residual,
    is_oscillating,
)
from .response_modulus import ResponseModulusResult, measure_response_modulus
from .analytic_boundary import (
    AnalyticBoundary,
    ReferenceState,
    analytic_boundary,
    best_response,
    reference_state,
    solve_fixed_point,
)
from .multi_dealer_modulus import (
    CommonModeProbe,
    MeanFieldLimit,
    MultiDealerBoundary,
    common_mode_probe,
    identify_kappa,
    joint_jacobian,
    mean_field_boundary,
    measure_common_mode_modulus,
    measure_differential_modulus,
    multi_dealer_boundary,
    n_eff,
    run_joint_rrm,
    strong_coupling_limit,
    sweep_dealer_count,
)
from .robust_boundary import (
    RobustBoundaryResult,
    RobustCertificate,
    empirical_radius,
    finite_sample_radius,
    loglog_rate,
    measure_modulus_estimates,
    rate_check,
    robust_boundary,
    robust_certificate,
    sample_complexity,
)
from .factor_reduction import (
    FactorModulus,
    PerBondConstants,
    TruncationBound,
    factor_modulus,
    factorize_corr,
    gamma_inverse_woodbury,
    modulus_matrix,
    per_bond_constants,
    spectral_radius,
    spectral_radius_woodbury,
    sweep_global_factor,
    systemic_spectral_radius,
    truncation_error_bound,
)
from .metrics import MarketMetrics, compute_metrics
from .sweep import SweepPoint, SweepResult, load_sweep_spec, run_sweep

__all__ = [
    "classify_run",
    "empirical_lipschitz",
    "fixed_point_residual",
    "is_oscillating",
    "ResponseModulusResult",
    "measure_response_modulus",
    # analytic stability boundary (math-theory 1.1 foundation)
    "AnalyticBoundary",
    "ReferenceState",
    "analytic_boundary",
    "best_response",
    "reference_state",
    "solve_fixed_point",
    # multi-dealer / systemic risk (math-theory 1.3)
    "CommonModeProbe",
    "MeanFieldLimit",
    "MultiDealerBoundary",
    "common_mode_probe",
    "identify_kappa",
    "joint_jacobian",
    "mean_field_boundary",
    "measure_common_mode_modulus",
    "measure_differential_modulus",
    "multi_dealer_boundary",
    "n_eff",
    "run_joint_rrm",
    "strong_coupling_limit",
    "sweep_dealer_count",
    # distributionally robust boundary (math-theory 1.4)
    "RobustBoundaryResult",
    "RobustCertificate",
    "empirical_radius",
    "finite_sample_radius",
    "loglog_rate",
    "measure_modulus_estimates",
    "rate_check",
    "robust_boundary",
    "robust_certificate",
    "sample_complexity",
    # factor-model scaling (math-theory 1.5)
    "FactorModulus",
    "PerBondConstants",
    "TruncationBound",
    "factor_modulus",
    "factorize_corr",
    "gamma_inverse_woodbury",
    "modulus_matrix",
    "per_bond_constants",
    "spectral_radius",
    "spectral_radius_woodbury",
    "sweep_global_factor",
    "systemic_spectral_radius",
    "truncation_error_bound",
    "MarketMetrics",
    "compute_metrics",
    "SweepPoint",
    "SweepResult",
    "load_sweep_spec",
    "run_sweep",
]
